---
- name: Verify services before start
  shell: pm2 list
  register: pm2_list

- name: Start services stock-trading-service
  shell: cd /data/stock-trading-service && pm2 start ./pm2/cluster.config.json
  when: "pm2_list.stdout.find('stock-trading-service') == -1"
#changed_when: "'stock-trading-service' not in pm2_list.stdout"


- name: Clear dump log
  shell: pm2 cleardump

- name: Startup services and save
  become: no
  shell: pm2 startup systemd -u iboard --hp /home/iboard && pm2 save

