#---
 - name: Verify services before stop
   shell: pm2 list
   register: pm2_list_out

 - name: Stop services stock-trading-service
   changed_when: "'stock-trading-service' in pm2_list_out.stdout"
   shell: pm2 stop stock-trading-service
#   when: "pm2_list_out.stdout.find('ssi-subscription') != 1"

 - name: Delete services stock-trading-service
   shell: pm2 delete stock-trading-service

 - name: Flush log
   shell: pm2 flush