#---ssi-priceboard services---#
- name: restart ssi-priceboard
  shell: pm2 restart ssi-priceboard
  
- name: stop ssi-priceboard
  shell: pm2 stop ssi-priceboard
  
- name: delete ssi-priceboard
  shell: pm2 delete ssi-priceboard

- name: pm2 sava
  shell: pm2 save

- name: start ssi-priceboard
  shell: cd /data/ssi-priceboard && pm2 start ./pm2/cluster.config.json



