---

- name: PlayBook for rollback update role on remote servers
  hosts:                    #Group servers need to rollback *Required
  vars:
    backup_path: ""             #Current backup path on remote server *Required
    app_path: ""                       #Current app path on remote server *Required
    env_file_path: ""  #Current env path on remote server need to rollback *Required
    current_folder:                           #Current folder need to remove on app folder *Required
        - 
        - 
    backup_folder:                            #Folder need to rollback to app folder *Required
        - 
        - 
  tasks:
  roles:
    - rollback

