#---stock-trading-service---#
#Start
- name: start stock-trading-service
  shell: cd /data/stock-trading-service && pm2 start ./pm2/cluster.config.json

#Stop
- name: stop stock-trading-service
  shell: pm2 stop stock-trading-service

#Restart
- name: restart stock-trading-service
  shell: pm2 restart stock-trading-service

#Delete  
- name: delete stock-trading-service
  shell: pm2 delete stock-trading-service

#---schedule-trading-reset---#
#Start
#- name: start schedule-trading-reset
#  shell: cd /data/stock-trading-service && pm2 start ./pm2/cluster.config.json

#Stop
- name: stop schedule-trading-reset
  shell: pm2 stop schedule-trading-reset

#Restart
- name: restart schedule-trading-reset
  shell: pm2 restart schedule-trading-reset

#Delete  
- name: delete schedule-trading-reset
  shell: pm2 delete schedule-trading-reset

#---stock-trading-streaming---#
#Stop
- name: stop stock-trading-streaming
  shell: pm2 stop stock-trading-streaming

#Restart
- name: restart stock-trading-streaming
  shell: pm2 restart stock-trading-streaming

#Delete  
- name: delete stock-trading-streaming
  shell: pm2 delete stock-trading-streaming

#---stock-bond-token---#
#Stop
- name: stop stock-bond-token
  shell: pm2 stop stock-bond-token

#Restart
- name: restart stock-bond-token
  shell: pm2 restart stock-bond-token

#Delete  
- name: delete stock-bond-token
  shell: pm2 delete stock-bond-token

#---term-deposit-token---#
#Stop
- name: stop term-deposit-token
  shell: pm2 stop term-deposit-token

#Restart
- name: restart term-deposit-token
  shell: pm2 restart term-deposit-token

#Delete  
- name: delete term-deposit-token
  shell: pm2 delete term-deposit-token

#---stock-otp-token---#
#Stop
- name: stop stock-otp-token
  shell: pm2 stop stock-otp-token

#Restart
- name: restart stock-otp-token
  shell: pm2 restart stock-otp-token

#Delete  
- name: delete stock-otp-token
  shell: pm2 delete stock-otp-token

#Flush log
- name: flush log
  shell: pm2 flush

#Clear dump pm2
- name: clear dump
  shell: pm2 cleardump

#Startup services
- name: startup services
  shell: pm2 startup

#Save services
- name: save services
  shell: pm2 save