---
- name: Verify services ssi-stock-gateway before start
  shell: pm2 list
  register: pm2_list

- name: Start services ssi-stock-gateway
  shell: cd /data/stock-gateway-service && pm2 start ./pm2/cluster.config.json
  when: "pm2_list.stdout.find('ssi-stock-gateway') == -1"
#changed_when: "'ssi-subscription' not in pm2listout2.stdout"


- name: Clear dump log
  shell: pm2 cleardump

- name: Startup services and save
  become: no
  shell: pm2 startup systemd -u iboard --hp /home/iboard && pm2 save

