#---
 - name: Verify services ssi-stock-gateway
   shell: pm2 list
   register: pm2_list_out

 - name: Stop services ssi-stock-gateway
   changed_when: "'ssi-stock-gateway' in pm2_list_out.stdout"
   shell: pm2 stop ssi-stock-gateway
#   when: "pm2_list_out.stdout.find('ssi-subscription') != 1"

 - name: Delete services ssi-stock-gateway
   shell: pm2 delete ssi-stock-gateway

 - name: Flush log
   shell: pm2 flush