---
 # tasks file for roles/backup
  - name: Create a directory if it does not exist
    file:
     path: "{{ backup_path }}/{{ansible_date_time.date}}"
     state: directory
     mode: '0755'
    remote_src: yes
    register: backup_dir
    
  - name: Create a backup tar.gz archive of a single file.
    archive:
     path: "{{ app_path }}/{{ item }}"
     dest: "{{backup_dir.path}}/{{item}}_{{ansible_date_time.date}}.tar.gz"
     format: gz
#     force_archive: true
     remote_src: yes
    with_items: "{{List_Of_Directories}}"
    
  - name: Copy file env to backup folder
    copy:
     src: "{{ env_file_path }}/.env"
     dest: "{{backup_dir.path}}/env_{{ansible_date_time.date}}"
     remote_src: yes
