#---
 - name: Verify services subscription
   shell: pm2 list
   register: pm2_list_out

 - name: Stop services subscription
   changed_when: "'ssi-subscription' in pm2_list_out.stdout"
   shell: pm2 stop ssi-subscription
#   when: "pm2_list_out.stdout.find('ssi-subscription') == 1"

 - name: Delete services subscription
   shell: pm2 delete ssi-subscription

 - name: Flush log
   shell: pm2 flush