#---
 - name: Verify services ssi-stock-query
   shell: pm2 list
   register: pm2_list_out

 - name: Stop services ssi-stock-query
   changed_when: "'ssi-stock-query' in pm2_list_out.stdout"
   shell: pm2 stop ssi-stock-query
#   when: "pm2_list_out.stdout.find('ssi-subscription') != 1"

 - name: Delete services query
   shell: pm2 delete ssi-stock-query

 - name: Flush log
   shell: pm2 flush