---
 # Backup folder/file before update
  - name: Create a directory if it does not exist
    file:
     path: "{{ backup_path }}/{{ ansible_date_time.date }}"
     state: directory
     mode: '0755'
    remote_src: yes
    register: backup_dir
    
  - name: Create a backup tar.gz archive of folders.
    archive:
     path: "{{ app_path }}/{{ item }}"
     dest: "{{ backup_dir.path }}/{{ item }}_{{ ansible_date_time.date }}.tar.gz"
     format: gz
#     force_archive: true
     remote_src: yes
    with_items: "{{ directories_list }}"
    
  - name: Create a backup of env file
    copy:
     src: "{{ env_config_path }}/env-config.js"
     dest: "{{ backup_dir.path }}/env-config_{{ansible_date_time.date}}"
     remote_src: yes