#---ssi-subscription service---#
#Start
- name: start ssi-subscription
  shell: cd /data/stock-subscription && pm2 start ./pm2/cluster.config.json

- name: start schedule-reset
  shell: pm2 start pm2/schedule-reset.json

- name: start schedule-update-index
  shell: pm2 start pm2/schedule-update.json

- name: start schedule-update-session-pre
  shell: pm2 start pm2/schedule-update-session-pre.json

- name: start schedule-update-top-stock
  shell: pm2 start pm2/schedule-update-top-stock.json

#Stop
- name: stop ssi-subscription
  shell: pm2 stop ssi-subscription

- name: stop schedule-reset
  shell: pm2 stop schedule-reset

- name: stop schedule-update-index
  shell: pm2 stop schedule-update-index

- name: stop schedule-update-session-pre
  shell: pm2 stop schedule-update-session-pre

- name: stop schedule-update-top-stock
  shell: pm2 stop schedule-update-top-stock

#Restart
- name: restart ssi-subscription
  shell: pm2 restart ssi-subscription

- name: restart schedule-reset
  shell: pm2 restart schedule-reset

- name: restart schedule-update-index
  shell: pm2 restart schedule-update-index

- name: restart schedule-update-session-pre
  shell: pm2 restart schedule-update-session-pre

- name: restart schedule-update-top-stock
  shell: pm2 restart schedule-update-top-stock

#Delete  
- name: delete ssi-subscription
  shell: pm2 delete ssi-subscription

- name: delete schedule-reset
  shell: pm2 delete schedule-reset

- name: delete schedule-update-index
  shell: pm2 delete schedule-update-index

- name: delete schedule-update-session-pre
  shell: pm2 delete schedule-update-session-pre

- name: delete schedule-update-top-stock
  shell: pm2 delete schedule-update-top-stock

#Flush log
- name: flush log
  shell: pm2 flush

#Clear dump pm2
- name: clear dump
  shell: pm2 cleardump

#Startup services
- name: startup services
  shell: pm2 startup

#Save services
- name: save services
  shell: pm2 save